#!/Users/gmax/usr/local/bin/bash

#-----------------------------------------
SBDIR="/Users/gmax/sandboxes/msb_5_1_34"
. "$SBDIR/sandbox_env"
#-----------------------------------------

if [ -f $PIDFILE ]
then
    if [ -f $SBDIR/data/master.info ]
    then
        echo "stop slave" | $SBDIR/use -u root
    fi
    $MYSQL_ADMIN --defaults-file=$SBDIR/my.sandbox.cnf shutdown
    sleep 1
fi
if [ -f $PIDFILE ]
then
    $SBDIR/send_kill
fi
