#!/Users/gmax/usr/local/bin/bash

#-----------------------------------------
SBDIR="/Users/gmax/sandboxes/msb_5_1_34"
. "$SBDIR/sandbox_env"
#-----------------------------------------

if [ -f $PIDFILE ]
then
    $MYSQL --defaults-file=$SBDIR/my.sandbox.cnf $MYCLIENT_OPTIONS "$@"
fi
